preload = ~/dotfiles/wallpapers/sunset-synthwave-sports-car-city-palm-trees-digital-art-4k-wallpaper-uhdpaper.com-216@1@n.jpg
wallpaper = DP-1, ~/dotfiles/wallpapers/sunset-synthwave-sports-car-city-palm-trees-digital-art-4k-wallpaper-uhdpaper.com-216@1@n.jpg
wallpaper = DP-2, ~/dotfiles/wallpapers/sunset-synthwave-sports-car-city-palm-trees-digital-art-4k-wallpaper-uhdpaper.com-216@1@n.jpg
splash = false
