# See https://wiki.hyprland.org/Configuring/Workspace-Rules/

workspace = 1, name:main,   monitor:DP-3, default:true, layoutopt:orientation:left
workspace = 2, name:social, monitor:DP-2, default:true, layoutopt:orientation:top

windowrule = workspace social, class:teams-for-linux
windowrule = workspace social, class:Spotify
windowrule = workspace social, class:discord
windowrule = workspace main,   class:com.mitchellh.ghostty

# Suppress fullscreen on open
windowrulev2 = suppressevent maximize, class:.*

# Set mouse to center monitor
exec-once = hyprctl dispatch workspace main
